### ISSUE TITLE
Support Material UI

### ISSUE THREAD

**Issue by matheusslg** [root913/tinymce-plugin-grid#14]
Hey, can we add support for Material UI Grid? It would be great if it's possible!

**Comment by root913** [comment]
Hey, can You please provide more information - link to docs/examples. I'll check it out.

**Comment by matheusslg** [comment]
@root913 sorry for the late to answer. I was requesting the feature to use the Material UI breakpoints. Take a look at https://mui.com/material-ui/customization/breakpoints/

**Comment by root913** [comment]
I've checked documentation and i don't think this is possible. 
Material UI from what i see generates dynamically styles so i cannot generate correct HTML.

This plugin generates HTML of grid with correct class names that correspondes with given ui framework.
